### ISSUE TITLE
react-vertex is nominee for OSAwards 2020 at React Summit 

### ISSUE THREAD

**Issue by fejes713** [sghall/react-vertex#6]
Hi @sghall

I couldn't find your email anywhere on the web so I am contacting you via this issue 😁

Your project **react-vertex** has been nominated for React Open Source Awards as part of [React Summit Conference](https://reactsummit.com/). 

Could you please give me some contact where I can send you all the details and tickets for React Summit?

Best,
Stefan

**Comment by sghall** [comment]
Ha.  Was just cleaning this up and saw this.  My apologies @fejes713.  That's fantastic.   Yeah, guess I missed that one.  Life got in the way of open source stuff for awhile there.  Going to try and rebuild this on WebGPU in the coming months.
